export const evidenziati = [
    'one-piece-c',
    'naruto-shippuden-c',
    'detective-conan-a',
    'boruto', 'naruto-c',
    'fairy-tail-a',
    'dragon-ball-z-c',
    'hunter-x-hunter-2011-a',
    'bleach-a',
    'dragon-ball-super-a',
    'black-clover',
    'pokemon-a',
    'gintama-a',
    'inuyasha-a',
    'fullmetal-alchemist-a'
];
export const suggeriti = [
    'dr-stone',
    'mahoutsukai-no-yome',
    'bungou-stray-dogs',
    'zatch-bell',
    'ultimate-muscle',
    'guilty-crown',
    'capeta',
    'quan-zhi-gao-shou',
    'death-note-a',
    'goblin-slayer',
    'gto-great-teacher-onizuka',
    'boku-dake-ga-inai-machi-erased-a',
    'kiseijuu-sei-no-kakuritsu'
];

export const generi = [
    'Tutti',
    'Arti marziali',
    'Avventura',
    'Azione',
    'Bambini',
    'Commedia',
    'Crimine',
    'Demenziale',
    'Demoni',
    'Dramma',
    'Ecchi',
    'Fantascienza',
    'Fantasy',
    'Giallo',
    'Harem',
    'Hentai',
    'Horror',
    'Josei',
    'Magia',
    'Mecha',
    'Militare',
    'Mistero',
    'Musica',
    'Parodia',
    'Poliziesco',
    'Psicologico',
    'Samurai',
    'Scuola',
    'Seinen',
    'Sentimentale',
    'Shojo',
    'Shonen',
    'Slice of life',
    'Sovrannaturale',
    'Spazio',
    'Sport',
    'Storico',
    'Superpoteri',
    'Vampiri',
    'Videogame',
    'Yaoi'
];

export const ordini = [
    'A-Z',
    'Z-A',
    'Più episodi',
    'Meno episodi'
];
